FROM python:3.7.10-slim

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/server/pylibrs/
ENV PYTHONPATH=$PYTHONPATH:/server/pylibrs/
ENV IS_RP=1

WORKDIR /server

RUN apt update && apt install -y libusb-1.0-0-dev libturbojpeg0 tar&& rm -rf /var/lib/apt/lists/*
COPY . .
RUN ls && tar -xzf pylibrs.tar.xz && rm pylibrs.tar.xz

RUN pip install numpy redis PyTurboJPEG

CMD ["python", "server.py"]
