pipeline {
    agent {
       label "deploy" 
    }
    stages {
          stage("connect") {
             steps {
               script {
                   sh '''
                   make image VERSION=cam_data_rp4 BRANCH=null FILE=./Dockerfile.rp4
                   make push VERSION=cam_data_rp4
                   make pull VERSION=cam_data_rp4 
                   '''
                   
               }
             }
          }
        }
}
